config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  ## User
  devise_for :user, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
                    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:edit, :update]
  get ':id/profile' => 'users#show',  as: :user_profile
  get ':id/posts'    => 'posts#index', as: :user_made
  get ':id/setting' => 'users#edit', as: :user_setting
  match ':id/setting' => 'users#update', via: [:put, :patch]
  get ':id/change_password' => 'users#edit_password', as: :user_change_password
  match ':id/change_password' => 'users#update_password', via: [:put, :patch]

  ## Posts
  resources :posts, except: [:index] do
    resources :comments, only: [:create]
  end
  get 'posts' => 'home#index'

  get 'categories/:category', to: 'home#index', as: :category

  get 'tags/:tag', to: 'home#index', as: :tag

  ## Comments
  resources :comments, only: [:edit, :update, :destroy]

  ## Votes
  get ':model/:id/vote/up' => 'votes#upvote', as: :upvote
  get ':model/:id/vote/down' => 'votes#downvote', as: :downvote
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :content, presence: true

  acts_as_votable

  delegate :name, :image, to: :user, prefix: true

  def editable_by?(user)
    user && user == self.user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    respond_to do |format|
      if @comment.save
        format.js { render 'create', locals: { counts: Comment.all.size } }
      else
        format.js { render 'create_error' }
      end
    end
  end

  def edit
    respond_to { |format| format.js }
  end

  def update
    respond_to do |format|
      @comment.update(comment_params) ? format.js : format.js { render 'edit' }
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.js do
        render 'destroy', locals: { counts: Comment.all.size, id: params[:id] }
      end
    end
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/views/comments/_create_form.html.slim
= bootstrap_form_for comment, url: post_comments_path(post, comment), remote: true do |f|
  = f.text_area :content, hide_label: true, placeholder: 'Leave a comment...'
  = f.hidden_field :user_id, value: current_user.id
  = f.form_group class: 'text-right' do
    = f.primary t(:create)

app/views/comments/_create_form_modal.html.slim
#comment_form_modal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal"
          span aria-hidden="true" &times;
          span.sr-only Close
        h4.modal-title= t(:new_comment)
      .modal-body
        = render partial: 'comments/create_form', locals: { post: post, comment: comment }

app/views/comments/_edit_form.html.slim
= bootstrap_form_for comment, remote: true do |f|
  = f.text_area :content, hide_label: true, placeholder: 'Leave a comment...'
  = f.form_group do
    = f.primary t(:update)

app/views/comments/_item.html.slim
.comment data-id=comment.id
  = render partial: 'comments/item_content', locals: { comment: comment }

app/views/comments/_item_content.html.slim
.commented_by
  .vote-box.pull-left data-id=comment.id
    = render partial: 'votes/vote_box', locals: { votable: comment }
  a.avatar.pull-left href="#"
    = avatar_image comment.user_image
  h2.username.pull-left= comment.user_name
  - comment.user.omniauths.each do |omniauth|
    a.user-link.pull-left href=omniauth.url target="_blank"
      = "@#{omniauth.provider.camelize}"
  span.comment-time.pull-left
    =' t(:comment_at)
    = timeago(comment.created_at)
  -if comment.editable_by? current_user
    .acts.pull-left
      =' link_button fa_icon('edit fw'), url: edit_comment_path(comment), color: 'danger', size: 'xs', remote: true
      = link_button fa_icon('trash fw'), url: comment_path(comment), method: 'delete', data: {confirm: t(:are_you_sure)}, color: 'danger', size: 'xs', remote: true
.content= comment.content

app/views/comments/create.js.erb
$('#comment_form_modal').modal('hide');
$('#comment_form_modal .modal-body').html("<%= escape_javascript(render 'create_form', post: @post, comment: Comment.new) %>");
$('.comments .counts > span').html('<%= counts %>');
$('.comments .list').append("<%= escape_javascript(render 'item', comment: @comment) %>");
$('abbr.timeago').timeago();

app/views/comments/create_error.js.erb
$('#comment_form_modal .modal-body').html("<%= escape_javascript(render 'create_form', post: @post, comment: @comment) %>");

app/views/comments/destroy.js.erb
$('.comments .counts > span').html('<%= counts %>');
$('.comment[data-id="<%= id %>"]').remove();

app/views/comments/edit.js.erb
$('.comment[data-id="<%= @comment.id %>"]').html("<%= escape_javascript(render 'edit_form', comment: @comment) %>");

app/views/comments/update.js.erb
$('.comment[data-id="<%= @comment.id %>"]').html("<%= escape_javascript(render 'item_content', comment: @comment) %>");
$('abbr.timeago').timeago();