config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  ## User
  devise_for :user, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
                    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:edit, :update]
  get ':id/profile' => 'users#show',  as: :user_profile
  get ':id/posts'    => 'posts#index', as: :user_made
  get ':id/setting' => 'users#edit', as: :user_setting
  match ':id/setting' => 'users#update', via: [:put, :patch]
  get ':id/change_password' => 'users#edit_password', as: :user_change_password
  match ':id/change_password' => 'users#update_password', via: [:put, :patch]

  ## Posts
  resources :posts, except: [:index] do
    resources :comments, only: [:create]
  end
  get 'posts' => 'home#index'

  get 'categories/:category', to: 'home#index', as: :category

  get 'tags/:tag', to: 'home#index', as: :tag

  ## Comments
  resources :comments, only: [:edit, :update, :destroy]

  ## Votes
  get ':model/:id/vote/up' => 'votes#upvote', as: :upvote
  get ':model/:id/vote/down' => 'votes#downvote', as: :downvote
end

app/models/user.rb
class User < ActiveRecord::Base
  include OmniauthCallbacks

  has_many :posts
  has_many :comments

  acts_as_voter

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable,
         :omniauthable, omniauth_providers: [:facebook, :github]

  def name
    self.email.split(/@/).first
  end

  def to_param
    "#{id} #{name}".to_slug.normalize.to_s
  end

  def image
    omniauths.first.image
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def auth
    @user = User.find_or_create_by_omniauth(env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect(@user, event: :authentication)
    else
      session['devise.omniauth_data'] = env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  User.omniauth_providers.each do |provider|
    alias_method provider, :auth
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_owner!, except: [:show]
  before_filter :set_user

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_profile_path(current_user)
    else
      render 'edit'
    end
  end

  def edit_password
  end

  def update_password
    if @user.update(user_change_password_params)
      sign_in :user, @user, bypass: true
      redirect_to user_profile_path(@user)
    else
      render 'edit_password'
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:intro)
    end

    def user_change_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    def authenticate_owner!
      redirect_to root_path unless user_signed_in? && current_user.to_param == params[:id]
    end
end

app/views/users/_user_profile.html.slim
.user-profile
  .container
    .user-avatar.pull-left
      a.avatar href=user_profile_path(@user)
        = avatar_image user.image
    .user-info.pull-left
      h1.title
        =' user.name
        small= "##{user.id}"
      h2.intro
        = user.intro
      .link
        - user.omniauths.each do |omniauth|
          a' href=omniauth.url target="_blank"
            = "@#{omniauth.provider.camelize}"
    .clearfix
    nav.navigation role="navigation"
      ul.nav.nav-tabs
        li.active role="presentation"
          a href="#" Upvoted
        li role="presentation"
          a href=user_made_path(user) Made
        li role="presentation"
          a href="#" Followers
        li role="presentation"
          a href="#" Following

app/views/users/edit.html.slim
.container
  .page-header
    h3
      = t :my_setting
  = bootstrap_form_for @user, url: user_setting_path, html: { method: :put }, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-4' do |f|
    = f.static_control :email
    = f.text_field :intro, placeholder: 'My Introduction', control_col: 'col-sm-6'
    = f.form_group do
      =' f.primary t(:update)
      = link_to t(:cancel), user_profile_path(current_user), class: 'btn btn-default'

app/views/users/edit_password.html.slim
.container
  .page-header
    h3
      = t :change_password
  = bootstrap_form_for @user, url: user_change_password_path, html: { method: :put }, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-4' do |f|
    = f.password_field :password, placeholder: 'Password', prepend: fa_icon('key fw'), autocomplete: 'off', autofocus: true
    = f.password_field :password_confirmation, placeholder: 'Password Confirmation', prepend: fa_icon('key fw'), autocomplete: 'off'
    = f.form_group do
      =' f.primary t(:update)
      = link_button t(:cancel), url: user_profile_path

app/views/users/show.html.slim
= render partial: 'users/user_profile', locals: { user: @user }