config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  ## User
  devise_for :user, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'signup' },
                    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :users, only: [:edit, :update]
  get ':id/profile' => 'users#show',  as: :user_profile
  get ':id/posts'    => 'posts#index', as: :user_made
  get ':id/setting' => 'users#edit', as: :user_setting
  match ':id/setting' => 'users#update', via: [:put, :patch]
  get ':id/change_password' => 'users#edit_password', as: :user_change_password
  match ':id/change_password' => 'users#update_password', via: [:put, :patch]

  ## Posts
  resources :posts, except: [:index] do
    resources :comments, only: [:create]
  end
  get 'posts' => 'home#index'

  get 'categories/:category', to: 'home#index', as: :category

  get 'tags/:tag', to: 'home#index', as: :tag

  ## Comments
  resources :comments, only: [:edit, :update, :destroy]

  ## Votes
  get ':model/:id/vote/up' => 'votes#upvote', as: :upvote
  get ':model/:id/vote/down' => 'votes#downvote', as: :downvote
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validates :url, presence: true
  validates :intro, presence: true
  validates :category_id, presence: true

  acts_as_votable
  acts_as_taggable

  delegate :name, :image, to: :user, prefix: true

  def to_param
    "#{id} #{title}".to_slug.normalize.to_s
  end

  def self.category_with(name)
    category = Category.with_translations.where(name: name).first
    posts = !category.nil? ? category.posts : {}
    posts
  end

  def editable_by?(user)
    user && user == self.user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

  def index
    @user = User.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to user_made_path(current_user)
    else
      render 'new'
    end
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to user_made_path(current_user)
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to user_made_path(current_user)
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :url, :intro, :category_id, :tag_list)
    end
end

app/views/posts/_category_and_tags.html.slim
.row
  .col-md-12
    - unless post.tag_list.empty?
      .tag_list.pull-right
        =' fa_icon 'tags fw'
        = raw post.tag_list.map { |t| link_to t, tag_path(t), target: '_blank' }.join(', ')
    - if post.category
      .category.pull-right
        =' fa_icon 'bookmark fw'
        = link_to post.category.name, category_path(post.category.name), target: '_blank'

app/views/posts/_form.html.slim
= bootstrap_form_for post, layout: :horizontal, label_col: 'col-sm-2', control_col: 'col-sm-4' do |f|
  = f.text_field :title, placeholder: 'Production Title', autofocus: true
  = f.url_field :url, placeholder: 'Production Url'
  = f.text_field :intro, placeholder: 'Production Introduction', control_col: 'col-sm-6'
  = f.collection_select :category_id, Category.all, :id, :name, prompt: true
  = f.text_field :tag_list, help: t("help.post.tag_list")
  = f.form_group do
    =' f.primary t(:submit)
    = link_to t(:cancel), user_made_path(current_user), class: 'btn btn-default'

app/views/posts/_list.html.slim
.container
  ul.posts-list.list-unstyled.votable
    - posts.each do |post|
      li.post data-url=post_path(post)
        .row
          .col-md-9
            .vote-box.pull-left data-id=post.id
              = render partial: 'votes/vote_box', locals: { votable: post }
            .detail.pull-left
              a.title href=post.url target="_blank"
                = post.title
              p.intro = post.intro
          .col-md-3
            .options
              - if params[:controller] == 'posts' && post.editable_by?(current_user)
                .acts.pull-right
                  =' link_button fa_icon('edit fw'), url: edit_post_path(post), color: 'danger'
                  = link_button fa_icon('trash fw'), url: post_path(post), method: 'delete', data: {confirm: t(:are_you_sure)}, color: 'danger'
              a.comments.pull-right href=post_path(post)
                =' fa_icon 'comments-o'
                = post.comments.count
              a.avatar.pull-right href=user_profile_path(post.user)
                = avatar_image post.user_image
        = render partial: 'posts/category_and_tags', locals: { post: post }

app/views/posts/edit.html.slim
.container
  .page-header
    h3
      =' t :edit_post_header
  = render partial: 'posts/form', locals: { post: @post }

app/views/posts/index.html.slim
= render partial: 'users/user_profile', locals: { user: @user }
= render partial: 'posts/list', locals: { posts: @user.posts }

app/views/posts/new.html.slim
.container
  .page-header
    h3
      =' t :new_post_header
      small= t :new_post_header_subtext
  = render partial: 'posts/form', locals: { post: @post }

app/views/posts/show.html.slim
.post-show
  .container
    .posted-by
      a.avatar.pull-left href=user_profile_path(@post.user)
        = avatar_image @post.user_image
      span.post-time.pull-left
        = '由 ' + @post.user_name + ' 發表於 '
        = timeago @post.created_at
    .detail
      a.title href=@post.url target="_blank"
        = @post.title
      p.intro = @post.intro
    = render partial: 'posts/category_and_tags', locals: { post: @post }
    .comments.votable
      .counts
        = raw t(:comments_count, count: @post.comments.count)
        - if current_user
          = button t(:new_comment), color: 'primary', size: 'xs', 'data-toggle' => 'modal', 'data-target' => '#comment_form_modal'
          = render partial: 'comments/create_form_modal', :locals => { post: @post, comment: @comment}
      .list
        - @post.comments.each do |comment|
          = render partial: 'comments/item', locals: { comment: comment }